# Show help message
default:
	@just --list

# Build executable from single .c file by providing source file name
build target:
	@echo "🔨 Building {{target}}..."
	@clang -Wall -Wextra -Werror -pedantic -std=c2x -o {{trim_end_match(target, '.c')}} {{target}}
	@echo "✅ Built {{trim_end_match(target, '.c')}} successfully!"

# Build and run single .c file by providing source file name
run target:
	@just build {{target}}
	@echo "🚀 Running {{trim_end_match(target, '.c')}}..."
	@./"{{trim_end_match(target, '.c')}}"

# Build test files for BST lib
build-tests:
	@echo "🔨 Building tests..."
	@clang++ -std=c++17 -I. -Itests -I/usr/local/include bst.c tests/test_bst.cpp tests/test_main.cpp -o tests/bst_test -L/usr/local/lib -lgtest -lgtest_main -lpthread

# Run tests for BST lib
test: build-tests
	@echo "🧪 Running tests..."
	./tests/bst_test

# Remove BST lib executables
clean:
	@echo "🧹🪣 Doing a cleanup..."
	@rm -f bst tests/bst_test
	@echo "✅ Cleanup complete!"
